# Luthien consolidated configuration

# Active policy configuration
policy:
  class: "luthien_proxy.policies.tool_call_judge:LLMJudgeToolPolicy"
  config:
    model: "openai/gemma-scorer"
    api_base: "http://local-llm:4000/v1"
    api_key: "sk-luthien-dev-key"
    probability_threshold: 0.6
    temperature: 0.0
    max_tokens: 256
# policy:
#   class: "luthien_proxy.policies.noop:NoOpPolicy"
#   config: {}

# Other policy examples:
# policy:
#   class: "luthien_proxy.policies.all_caps:AllCapsPolicy"
#   config: {}
#
# policy:
#   class: "luthien_proxy.policies.noop:NoOpPolicy"
#   config: {}
# policy:
#   class: "luthien_proxy.policies.all_caps:AllCapsPolicy"
#   config: {}
