# Luthien consolidated configuration

# Active policy (module.path:ClassName)
# policy: "luthien_proxy.policies.logging:LoggingPolicy"
# policy: "luthien_proxy.policies.noop:NoOpPolicy"
policy: "luthien_proxy.policies.all_caps:AllCapsPolicy"

# Policy-specific options
policy_options:
  policy_specific_arg: 'someval'
