# Luthien consolidated configuration

# Active policy configuration
policy:
  class: "luthien_proxy.policies.noop:NoOpPolicy"
  config: {}

# Other policy examples:
# policy:
#   class: "luthien_proxy.policies.all_caps:AllCapsPolicy"
#   config: {}
#
# policy:
#   class: "luthien_proxy.policies.noop:NoOpPolicy"
#   config: {}
# policy:
#   class: "luthien_proxy.policies.all_caps:AllCapsPolicy"
#   config: {}
