# Luthien consolidated configuration

# Active policy configuration
# policy:
#   class: "luthien_proxy.policies.tool_call_judge:LLMJudgeToolPolicy"
#   config:
#     model: "ollama/gemma2:2b"
#     api_base: "http://local-llm:11434"
#     api_key: "ollama"
#     probability_threshold: 0.6
#     temperature: 0.0
#     max_tokens: 256
# V3 Tool Call Judge for e2e testing
policy:
  class: "luthien_proxy.v2.policies.tool_call_judge_v3:ToolCallJudgeV3Policy"
  config:
    model: "ollama/gemma2:2b"
    api_base: "http://local-llm:11434"
    api_key: "ollama"
    probability_threshold: 0.6
    temperature: 0.0
    max_tokens: 256

# No-op (default)
# policy:
#   class: "luthien_proxy.v2.policies.noop:NoOpPolicy"
#   config: {}

# Other policy examples:
# policy:
#   class: "luthien_proxy.policies.all_caps:AllCapsPolicy"
#   config: {}
#
# policy:
#   class: "luthien_proxy.policies.noop:NoOpPolicy"
#   config: {}
# policy:
#   class: "luthien_proxy.policies.all_caps:AllCapsPolicy"
#   config: {}
