# Luthien consolidated configuration

# Active policy (module.path:ClassName)
# policy: "luthien_control.policies.logging:LoggingPolicy"
# policy: "luthien_control.policies.noop:NoOpPolicy"
policy: "luthien_control.policies.all_caps:AllCapsPolicy"

# Policy-specific options
policy_options:
  stream:
    log_every_n: 1
