# Luthien consolidated configuration

# Active policy (module.path:ClassName)
policy: "luthien_control.policies.logging:LoggingPolicy"

# Policy-specific options
policy_options:
  stream:
    log_every_n: 1
