# Luthien consolidated configuration

# Active policy configuration
policy:
  class: "luthien_proxy.policies.streaming_separator:StreamingSeparatorPolicy"
  config:
    every_n: 1
    separator_str: "|"

# Other policy examples:
# policy:
#   class: "luthien_proxy.policies.all_caps:AllCapsPolicy"
#   config: {}
#
# policy:
#   class: "luthien_proxy.policies.noop:NoOpPolicy"
#   config: {}
