#!/usr/bin/env python3
"""Generate mock regression tests from real-API failure captures.

Usage:
    uv run python scripts/generate_mock_from_failures.py [--output PATH]

Reads every JSON file in tests/luthien_proxy/e2e_tests/failure_registry/ and emits a
pytest file whose tests replay the actual LLM responses that caused failures.
This turns non-deterministic real-API failures into deterministic mock
regression tests.

Workflow:
    1. Run real-API tests:
           uv run pytest -m e2e tests/luthien_proxy/e2e_tests/test_real_api_threat_scenarios.py -v
    2. Inspect captures:
           ls tests/luthien_proxy/e2e_tests/failure_registry/
    3. Generate mock tests:
           uv run python scripts/generate_mock_from_failures.py
    4. Run generated tests:
           uv run pytest -m mock_e2e tests/luthien_proxy/e2e_tests/test_mock_from_failures.py -v
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_DIR = _REPO_ROOT / "tests/luthien_proxy/e2e_tests/failure_registry"
DEFAULT_OUTPUT = _REPO_ROOT / "tests/luthien_proxy/e2e_tests/test_mock_from_failures.py"

_FILE_HEADER = '''\
"""Mock regression tests auto-generated from real-API failure captures.

AUTO-GENERATED by scripts/generate_mock_from_failures.py — do not edit.
Regenerate after adding new captures:
    uv run python scripts/generate_mock_from_failures.py

Each test replays an actual LLM response that caused a real-API test to fail,
making the failure deterministic and reproducible without API calls.

Run:
    uv run pytest -m mock_e2e tests/luthien_proxy/e2e_tests/test_mock_from_failures.py -v
"""

import httpx
import pytest
from tests.luthien_proxy.e2e_tests.conftest import API_KEY, GATEWAY_URL, policy_context
from tests.luthien_proxy.e2e_tests.mock_anthropic.responses import text_response
from tests.luthien_proxy.e2e_tests.mock_anthropic.server import MockAnthropicServer

pytestmark = pytest.mark.mock_e2e

_BASE_REQUEST = {
    "model": "claude-haiku-4-5",
    "messages": [{"role": "user", "content": "test"}],
    "max_tokens": 100,
    "stream": False,
}
_HEADERS = {"Authorization": f"Bearer {API_KEY}"}
'''


def _load_entries() -> list[dict]:
    entries: list[dict] = []
    for path in sorted(REGISTRY_DIR.glob("*.json")):
        try:
            data = json.loads(path.read_text())
            batch = data if isinstance(data, list) else [data]
            for entry in batch:
                entry["_source_file"] = path.name
            entries.extend(batch)
        except (json.JSONDecodeError, OSError) as exc:
            print(f"warning: skipping {path.name}: {exc}", file=sys.stderr)
    return entries


def _safe_name(raw: str, fallback: str = "failure") -> str:
    sanitized = "".join(c if c.isalnum() else "_" for c in raw).strip("_")[:60]
    return sanitized or fallback


def _render_test(entry: dict, index: int) -> str:
    """Render one regression test function from a failure capture entry.

    NOTE: actual_response and policy configs are embedded via repr() from the local
    failure registry (developer-only, never served from untrusted sources).
    policy_class_ref is taken directly from the capture — do not use generated tests
    from untrusted registries.
    """
    base_name = _safe_name(entry.get("test_name", f"failure_{index}"))
    fn_name = f"test_mock_regression_{index:03d}_{base_name}"
    scenario = entry.get("scenario", "unknown scenario").replace("\n", " ").replace("\r", "")
    expected = entry.get("expected", "")
    actual = entry.get("actual_response", "")
    policy_config = entry.get("policy_config", {})
    timestamp = entry.get("timestamp", "unknown")
    source = entry.get("_source_file", "unknown")

    if not expected:
        return f"""\
@pytest.mark.asyncio
async def {fn_name}(mock_anthropic: MockAnthropicServer, gateway_healthy):
    # Captured: {source} at {timestamp}
    # Scenario: {scenario}
    pytest.skip("No expected value in capture — cannot generate a meaningful assertion")
"""

    policy_class_ref = policy_config.get(
        "class_ref",
        "luthien_proxy.policies.simple_llm_policy:SimpleLLMPolicy",
    )
    if not policy_class_ref.startswith("luthien_proxy.policies."):
        raise ValueError(
            f"Refusing to generate test: policy_class_ref {policy_class_ref!r} does not "
            f"start with 'luthien_proxy.policies.' — capture file may be untrusted."
        )
    config = {k: v for k, v in policy_config.items() if k != "class_ref"}

    return f"""\
@pytest.mark.asyncio
async def {fn_name}(mock_anthropic: MockAnthropicServer, gateway_healthy):
    # Captured: {source} at {timestamp}
    # Scenario: {scenario}
    # Expected: {expected!r}
    # Actual LLM response: {actual!r}
    mock_anthropic.enqueue(text_response({actual!r}))

    async with policy_context({policy_class_ref!r}, {config!r}):
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(
                f"{{GATEWAY_URL}}/v1/messages",
                json=_BASE_REQUEST,
                headers=_HEADERS,
            )

    assert response.status_code == 200
    data = response.json()
    content = " ".join(
        b.get("text", "") for b in data.get("content", []) if b.get("type") == "text"
    )
    assert {expected!r} in content, f"Expected {{content!r}} to contain {expected!r}"
"""


def generate(output: Path) -> int:
    if not REGISTRY_DIR.exists():
        print(f"No failure registry at {REGISTRY_DIR}. Run real-API tests first.")
        return 1

    entries = _load_entries()
    if not entries:
        print("No failure entries found. Nothing to generate.")
        return 0

    tests = "\n\n".join(_render_test(e, i) for i, e in enumerate(entries))
    output.write_text(_FILE_HEADER + "\n\n" + tests + "\n")
    print(f"Generated {len(entries)} regression test(s) → {output}")
    return 0


def main() -> None:
    _doc = __doc__ or ""
    parser = argparse.ArgumentParser(description=_doc.splitlines()[0])
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output file (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()
    sys.exit(generate(args.output))


if __name__ == "__main__":
    main()
