"""Generate deterministic mock regression tests from FailureCapture JSON files.

When a real-API e2e test fails, the ``failure_capture`` fixture writes the actual
LLM response to ``tests/luthien_proxy/e2e_tests/failure_registry/``.  This script
reads those JSON files and emits pytest test stubs that replay the same scenario
against the mock Anthropic server — no real API calls, no non-determinism.

Usage::

    # Dry-run: print generated tests to stdout
    uv run python scripts/generate_mock_from_failures.py

    # Write to a file
    uv run python scripts/generate_mock_from_failures.py --output tests/luthien_proxy/e2e_tests/test_mock_regressions.py

    # Process a specific capture file
    uv run python scripts/generate_mock_from_failures.py path/to/capture.json

    # Preview without writing
    uv run python scripts/generate_mock_from_failures.py --dry-run --output test_regressions.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

_FAILURE_REGISTRY_DIR = Path(__file__).parent.parent / "tests" / "luthien_proxy" / "e2e_tests" / "failure_registry"

_FILE_HEADER = '''\
"""Auto-generated mock regression tests from FailureCapture records.

Generated by: scripts/generate_mock_from_failures.py
Do not edit by hand — re-run the script to regenerate after new failures are captured.
"""

import pytest
from tests.luthien_proxy.e2e_tests.conftest import (
    API_KEY,
    BASE_REQUEST,
    GATEWAY_URL,
    MOCK_HEADERS,
    SIMPLE_LLM_POLICY,
    collect_sse_text,
    judge_pass,
    judge_replace_text,
    policy_context,
)
from tests.luthien_proxy.e2e_tests.mock_anthropic.responses import text_response
from tests.luthien_proxy.e2e_tests.mock_anthropic.server import MockAnthropicServer
from tests.luthien_proxy.e2e_tests.mock_anthropic.simulator import ClaudeCodeSimulator

pytestmark = pytest.mark.mock_e2e
'''


def _sanitize_name(raw: str) -> str:
    """Convert an arbitrary string to a valid Python identifier."""
    name = re.sub(r"[^a-zA-Z0-9]+", "_", raw).strip("_").lower()
    if name and name[0].isdigit():
        name = f"test_{name}"
    return name or "unnamed"


def _uses_judge(policy_config: dict) -> bool:
    """Return True if the policy config drives a judge LLM (SimpleLLMPolicy)."""
    return "instructions" in policy_config or "model" in policy_config


def _render_test(entry: dict, seen_names: set[str]) -> str:
    """Render one FailureCapture entry as a pytest test function string."""
    raw_name = entry.get("test_name", "unknown")
    scenario = entry.get("scenario", "")
    policy_config = entry.get("policy_config", {})
    expected = entry.get("expected", "")
    actual_response = entry.get("actual_response", "")
    input_messages = entry.get("input_messages", [])
    timestamp = entry.get("timestamp", "")

    base = f"test_{_sanitize_name(raw_name)}_regression"
    name = base
    suffix = 1
    while name in seen_names:
        name = f"{base}_{suffix}"
        suffix += 1
    seen_names.add(name)

    user_content = ""
    for msg in input_messages:
        if msg.get("role") == "user":
            content = msg.get("content", "")
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        user_content = block["text"]
                        break
            else:
                user_content = str(content)
            break

    uses_judge = _uses_judge(policy_config)
    config_lines = json.dumps(policy_config, indent=4).split("\n")
    config_repr = "\n".join(config_lines[0:1] + ["    " + ln for ln in config_lines[1:]])

    lines = [
        "",
        "",
        "@pytest.mark.asyncio",
        f"async def {name}(mock_anthropic: MockAnthropicServer, gateway_healthy):",
        f'    """Regression: {scenario}',
        "",
        f"    Captured from: {raw_name}",
        f"    Timestamp: {timestamp}",
        '    """',
        f"    policy_config = {config_repr}",
        "",
        f"    mock_anthropic.enqueue(text_response({json.dumps(actual_response)}))",
    ]

    if uses_judge:
        lines.append(f"    mock_anthropic.enqueue(judge_replace_text({json.dumps(expected)}))")

    lines += [
        "",
        "    async with policy_context(SIMPLE_LLM_POLICY, policy_config):",
        "        session = ClaudeCodeSimulator(GATEWAY_URL, API_KEY)",
        f"        turn = await session.send({json.dumps(user_content or 'hello')})",
        "",
        f"    assert {json.dumps(expected)} in turn.text",
    ]

    return "\n".join(lines)


def load_entries(paths: list[Path]) -> list[dict]:
    """Load and flatten all entries from the given JSON capture files."""
    entries = []
    for path in paths:
        try:
            raw = json.loads(path.read_text())
            if isinstance(raw, list):
                entries.extend(raw)
            else:
                entries.append(raw)
        except (json.JSONDecodeError, OSError) as exc:
            print(f"WARNING: skipping {path}: {exc}", file=sys.stderr)
    return entries


def generate(entries: list[dict]) -> str:
    """Return the full Python source for the regression test file."""
    seen_names: set[str] = set()
    test_blocks = [_render_test(e, seen_names) for e in entries]
    return _FILE_HEADER + "\n".join(test_blocks) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "captures",
        nargs="*",
        type=Path,
        help="Specific failure capture JSON files to process. Defaults to all files in failure_registry/.",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Write generated tests to this file. Defaults to stdout.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without actually writing the file.",
    )
    args = parser.parse_args()

    if args.captures:
        paths = [Path(p) for p in args.captures]
    else:
        if not _FAILURE_REGISTRY_DIR.exists():
            print(f"No failure registry found at {_FAILURE_REGISTRY_DIR}", file=sys.stderr)
            sys.exit(0)
        paths = sorted(_FAILURE_REGISTRY_DIR.glob("*.json"))

    if not paths:
        print("No failure capture files found.", file=sys.stderr)
        sys.exit(0)

    entries = load_entries(paths)
    if not entries:
        print("No entries found in capture files.", file=sys.stderr)
        sys.exit(0)

    source = generate(entries)

    if args.output is None or args.dry_run:
        print(source)
    else:
        args.output.write_text(source)
        print(f"Wrote {len(entries)} regression test(s) to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
