# V3 Tool Call Judge Policy Configuration
# Uses EventBasedPolicy architecture for clean, simple implementation

policy:
  class: "luthien_proxy.v2.policies.tool_call_judge_v3:ToolCallJudgeV3Policy"
  config:
    model: "openai/judge-scorer"
    api_base: "http://dummy-provider:8080/v1"
    api_key: null
    probability_threshold: 0.6
    temperature: 0.0
    max_tokens: 256
